### ISSUE TITLE
Question - Animation.SlideDown

### ISSUE THREAD

**Issue by VaclavElias** [mikoskinen/Blazor.Animate#1]
Is possible it slides only e.g. 10px so it is just a small subtle transition?

By the way, great work! :)

Thank you.

**Comment by mikoskinen** [comment]
Thank you for the comment. 

Currently you have to modify the CSS in order to make the transitions more subtle. For example, if you want to edit SlideLeft-animation, first make sure that you include the interop-file and the site's css in the following order:

    <script src="_content/BlazorAnimate/blazorAnimateInterop.js"></script>
    <link href="css/site.css" rel="stylesheet" />

So interop first, then the site.css. The modified animations are defined in the site.css. For example:

```
[data-aos=slide-left] {
    transform: translate3d(25%,0,0);
}
```

This will give you the following result:

![aossmall](https://user-images.githubusercontent.com/143570/69166451-eb5c8680-0afb-11ea-94e2-0c7066c1765e.gif)

It should be possible to add a new feature to the library which would allow you to adjust the built-in animations (and to define new ones) using C#.

Here's how AOS by default defines the slide-animations:

```
[data-aos=slide-up] {
    transform: translate3d(0,100%,0)
}

[data-aos=slide-down] {
    transform: translate3d(0,-100%,0)
}

[data-aos=slide-right] {
    transform: translate3d(-100%,0,0)
}

[data-aos=slide-left] {
    transform: translate3d(100%,0,0)
}
```

For the complete list, you can check the AOS' repository: https://github.com/michalsnik/aos/blob/v2/dist/aos.css.

**Comment by VaclavElias** [comment]
Thank you, I see, so I can actually control it fully from css. 

Let's play a bit more with your Blazor.Animate and I will see if css is enough or a new feature would be better.

Perfect. Have a nice day!

**Comment by VaclavElias** [comment]
Thanks this worked!
